---
name: Build and publish a 🛢️ container

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: build-and-publish-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # minimal required permissions to clone repo

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      build_matrix: ${{ steps.set-build-matrix.outputs.build_matrix }}
      tag_matrix: ${{ steps.set-tag-matrix.outputs.tag_matrix }}
    steps:
      - name: Source checkout
        uses: actions/checkout@v6

      - name: 'Setup yq'
        uses: dcarbone/install-yq-action@v1.3.1

      - id: set-build-matrix
        run: echo "build_matrix=$(bash matrix.sh build)" >> $GITHUB_OUTPUT

      - id: set-tag-matrix
        run: echo "tag_matrix=$(bash matrix.sh tag)" >> $GITHUB_OUTPUT

  build-and-push-container:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.build_matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build ${{ matrix.os }} / ${{ matrix.platform }} container
        uses: voxpupuli/gha-build-and-publish-a-container@v2
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          build_args: |
            OPENVOX_RELEASE=${{ matrix.release }}
            OPENVOXSERVER_VERSION=${{ matrix.server_version }}
            OPENVOXDB_VERSION=${{ matrix.db_version }}
            RUBYGEM_R10K=${{ matrix.rubygem_r10k }}
            RUBYGEM_RUGGED=${{ matrix.rubygem_rugged }}
            JDK_VERSION=${{ matrix.jdk_version }}
          build_arch: linux/${{ matrix.platform }}
          build_context: .
          buildfile: Containerfile.${{ matrix.os }}
          # tag will look like: ghcr.io/openvoxproject/openvoxserver:8-<sha>-ubuntu-amd64
          tags: ghcr.io/openvoxproject/openvoxserver:${{ matrix.release }}-${{ github.sha }}-${{ matrix.os }}-${{ matrix.platform }}

  create-multi-arch-manifests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - setup-matrix
      - build-and-push-container
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.tag_matrix) }}
    steps:
      - name: Log in to the ghcr.io registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the docker.io registry
        uses: docker/login-action@v4
        with:
          registry: docker.io
          username: voxpupulibot
          password: ${{ secrets.DOCKERHUB_BOT_ADMIN_TOKEN }}

      - name: Create ref-specific multi-arch manifests
        run: |
          # tag will look like: ghcr.io/openvoxproject/openvoxserver:8.13.0-v1.2.3
          # tag will look like: ghcr.io/openvoxproject/openvoxserver:8.13.0-main
          # tag will look like: ghcr.io/openvoxproject/openvoxserver:8.13.0
          # tag will look like: ghcr.io/openvoxproject/openvoxserver:8
          docker buildx imagetools create \
            -t ghcr.io/openvoxproject/openvoxserver:${{ matrix.server_version }}-${{ github.ref_name }} \
            -t ghcr.io/openvoxproject/openvoxserver:${{ matrix.server_version }} \
            -t ghcr.io/openvoxproject/openvoxserver:${{ matrix.release }} \
            -t docker.io/voxpupuli/openvoxserver:${{ matrix.server_version }}-${{ github.ref_name }} \
            -t docker.io/voxpupuli/openvoxserver:${{ matrix.server_version }} \
            -t docker.io/voxpupuli/openvoxserver:${{ matrix.release }} \
            ghcr.io/openvoxproject/openvoxserver:${{ matrix.release }}-${{ github.sha }}-ubuntu-arm64 \
            ghcr.io/openvoxproject/openvoxserver:${{ matrix.release }}-${{ github.sha }}-ubuntu-amd64

          # tag will look like: ghcr.io/openvoxproject/openvoxserver:8.13.0-v1.2.3-alpine
          # tag will look like: ghcr.io/openvoxproject/openvoxserver:8.13.0-main-alpine
          # tag will look like: ghcr.io/openvoxproject/openvoxserver:8.13.0-alpine
          # tag will look like: ghcr.io/openvoxproject/openvoxserver:8-alpine
          docker buildx imagetools create \
            -t ghcr.io/openvoxproject/openvoxserver:${{ matrix.server_version }}-${{ github.ref_name }}-alpine \
            -t ghcr.io/openvoxproject/openvoxserver:${{ matrix.server_version }}-alpine \
            -t ghcr.io/openvoxproject/openvoxserver:${{ matrix.release }}-alpine \
            -t docker.io/voxpupuli/openvoxserver:${{ matrix.server_version }}-${{ github.ref_name }}-alpine \
            -t docker.io/voxpupuli/openvoxserver:${{ matrix.server_version }}-alpine \
            -t docker.io/voxpupuli/openvoxserver:${{ matrix.release }}-alpine \
            ghcr.io/openvoxproject/openvoxserver:${{ matrix.release }}-${{ github.sha }}-alpine-arm64 \
            ghcr.io/openvoxproject/openvoxserver:${{ matrix.release }}-${{ github.sha }}-alpine-amd64

      - name: Update floating multi-arch tags
        if: github.ref == 'refs/heads/main'
        run: |
          # Ubuntu is the default variant and therefore has no OS suffix.
          docker buildx imagetools create \
            -t ghcr.io/openvoxproject/openvoxserver:latest \
            -t docker.io/voxpupuli/openvoxserver:latest \
            ghcr.io/openvoxproject/openvoxserver:${{ matrix.release }}-${{ github.sha }}-ubuntu-arm64 \
            ghcr.io/openvoxproject/openvoxserver:${{ matrix.release }}-${{ github.sha }}-ubuntu-amd64

          docker buildx imagetools create \
            -t ghcr.io/openvoxproject/openvoxserver:latest-alpine \
            -t docker.io/voxpupuli/openvoxserver:latest-alpine \
            ghcr.io/openvoxproject/openvoxserver:${{ matrix.release }}-${{ github.sha }}-alpine-arm64 \
            ghcr.io/openvoxproject/openvoxserver:${{ matrix.release }}-${{ github.sha }}-alpine-amd64

  update-dockerhub-description:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs:
      - create-multi-arch-manifests
    steps:
      - name: Source checkout
        uses: actions/checkout@v6

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: voxpupulibot
          password: ${{ secrets.DOCKERHUB_BOT_ADMIN_TOKEN }}
          repository: voxpupuli/openvoxserver
